version: '3.9'

services:
  user:
    build: ./user
    container_name: user
    command: ["python", "./wait-for-db.py", "python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=userdb
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=db-user
      - DB_PORT=5432
    depends_on:
      - db-user
    volumes:
      - ./user:/app

  db-user:
    image: postgres:16
    container_name: db-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data

volumes:
  user_data:

