services:
  user:
    build: ./user
    container_name: user
    command: >
        sh -c "
          python manage.py migrate &&
          python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8001:8000"
    environment:
      - DB_NAME=userdb
      - DB_USER=user
      - DB_PASSWORD=pass
      - DB_HOST=db-user
      - DB_PORT=5432
    depends_on:
      - db-user
    volumes:
      - ./user:/app

  db-user:
    image: postgres:16
    container_name: db-user
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5433:5432"
    volumes:
      - user_data:/var/lib/postgresql/data
      
  budgets:
    build: ./budgets
    container_name: budgets
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-budgets:5432/budgetsdb
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: pass
    depends_on:
      - db-budgets

  db-budgets:
    image: postgres:16
    container_name: db-budgets
    environment:
      POSTGRES_DB: budgetsdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5434:5432"
    volumes:
      - budgets_data:/var/lib/postgresql/data    
  

volumes:
  user_data:
  budgets_data:

